on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Release-Please: crea la nueva versión y changelog
      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple

      # Paso 3: Crear el tag del release
      - name: Create release tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.release-please.outputs.release_tag }}
