name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Usa la versión 3
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple
      - name: Create Release
        if: ${{ steps.release.outputs.release_created }} # Condición crucial
        uses: ncipollo/release-action@v1 # o actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          release_name: ${{ steps.release.outputs.release_name }}
          body: ${{ steps.release.outputs.body }}
          draft: false
          prerelease: ${{ steps.release.outputs.prerelease }}
